### ISSUE TITLE
Vendor font not published

### ISSUE THREAD

**Issue by rickmills** [Johnathan/nova-trumbowyg#1]
Hi,

Installed this on a fresh nova instance to give it a try, and followed the instructions, however the font for the wysiwyg points to a 404: 

```nova-trumbowyg:1 GET http://nova.test/fonts/vendor/trumbowyg/dist/ui/icons.svg?a61f908579a2fc1a4ead0508c599dd2f 404 (Not Found)```

Looks like the font just isn't being published and theres no instructions on how to do so. It doesn't show up under `php artisan vendor:publish` as an option, and a npm run or watch doesnt do anything either.

**Comment by Johnathan** [comment]
Hi @rickmills,

Thanks for the report. This should be fixed now if you want to try update to the latest version. Just run `php artisan vendor:publish --tag=public `

Thanks!
