### ISSUE TITLE
Quick Fix For 100% Width Enhancement

### ISSUE THREAD

**Issue by nickpoulos** [Johnathan/nova-trumbowyg#10]
Just learned of a quick trick for custom components that I think would be beneficial for this field.  In your main FormField.vue file, if you add the following -- :full-width-content="true" to your <default template> tag, it will create a full width component, instead of instead a .w-1/2 which gives a 50% width. 

I could make a PR myself, but such a small change I thought it might be easier for you.

**Comment by Johnathan** [comment]
@nickpoulos PR would be good 👍 

Configureable as well be default to 100%

**Comment by nickpoulos** [comment]
You got it bro.  Lemme write it up i should have something later today 👍

**Comment by aihowes** [comment]
Can't see a PR made for this? Has this been done at all, if not I can submit a PR later this evening if it's still open?

**Comment by Johnathan** [comment]
Hi @aihowes it hasn't been done yet, feel free to make a PR if you have the time!

**Comment by wize-wiz** [comment]
@aihowes that would be great, I'll scrap it off my todo list :)
