### ISSUE TITLE
Question Mark in field content jumps to Global Search

### ISSUE THREAD

**Issue by reado** [Johnathan/nova-trumbowyg#6]
Hey!

Great plugin btw but I'm having troubles when using `?` within the content of my field.

Nova has a listener for when `?` is pressed and will jump to the global site search.  The solution to this was to halt any keydown events within the component from bubbling up to the global listener using `@keydown.stop` to stop propagation.  I tried to fix this myself thanks to information from [this issue request](https://github.com/laravel/nova-issues/issues/117#issuecomment-424777886) but I wasn't able to get it to work with my own experimenting.

If you have any suggestions on how to fix this, that would be a huge help

Thanks!

**Comment by Johnathan** [comment]
Thanks for the bug report @reado, I've just tagged 1.0.8 which should fix this issue!
