### ISSUE TITLE
Support for alwaysShow()

### ISSUE THREAD

**Issue by albalooshi** [Johnathan/nova-trumbowyg#9]
It would be nice a function to always showing the content while viewing it on the details similar to the default text area.

**Comment by Johnathan** [comment]
That would be nice, I’ll try to get around to it at some point. Happy to accept a pull request if you’d like to give it a go!

**Comment by wize-wiz** [comment]
> That would be nice, I’ll try to get around to it at some point. Happy to accept a pull request if you’d like to give it a go!

I just gave it a go :) .. johnathan/nova-trumbowyg#12

To clarify a bit, it's the same procedure as with field [Textarea](https://nova.laravel.com/docs/1.0/resources/fields.html#textarea-field)

```php
NovaTrumbowyg::make('textfield')
    // always shows the content 
    ->alwaysShow()
```
